// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgT3xcvgLDE2Xqldw7gv6GpsPCPJOH6E8',
    appId: '1:869678770162:web:799caa2ee328648a8ead6b',
    messagingSenderId: '869678770162',
    projectId: 'med-agenda-app-a9746',
    authDomain: 'med-agenda-app-a9746.firebaseapp.com',
    storageBucket: 'med-agenda-app-a9746.firebasestorage.app',
    measurementId: 'G-8W0ZGGQ01F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARZjGEVj_K0V1_thHBZpLyqTewEzn9fE8',
    appId: '1:869678770162:android:237a12fe5e10426c8ead6b',
    messagingSenderId: '869678770162',
    projectId: 'med-agenda-app-a9746',
    storageBucket: 'med-agenda-app-a9746.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5Jcp0W-yleHbsniIImool336-jvkJu1c',
    appId: '1:869678770162:ios:7cdfd9db8caa01fd8ead6b',
    messagingSenderId: '869678770162',
    projectId: 'med-agenda-app-a9746',
    storageBucket: 'med-agenda-app-a9746.firebasestorage.app',
    iosBundleId: 'com.example.medAgendaApp',
  );
}
